### ISSUE TITLE
Linux上提示 KeyError: 'streams'

### ISSUE THREAD

**Issue by tailangjun** [HaujetZhao/JumpCutter2#3]
$ JumpCutter2 ./20210916.mp4
正在导入 spleeter
2023-11-26 17:49:08.103908: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
spleeter 模型所在文件夹：/opt/anaconda3/envs/jumpcutter/lib/python3.9/site-packages/JumpCutter2/pretrained_models
总共有 1 个文件需要处理，正在处理第 1 个：./20210916.mp4
Traceback (most recent call last):
  File "/opt/anaconda3/envs/jumpcutter/bin/JumpCutter2", line 8, in <module>
    sys.exit(main())
  File "/opt/anaconda3/envs/jumpcutter/lib/python3.9/site-packages/JumpCutter2/__main__.py", line 65, in main
    处理(args)
  File "/opt/anaconda3/envs/jumpcutter/lib/python3.9/site-packages/JumpCutter2/__main__.py", line 253, in 处理
    处理文件(File, 参数, 分轨器)
  File "/opt/anaconda3/envs/jumpcutter/lib/python3.9/site-packages/JumpCutter2/__main__.py", line 258, in 处理文件
    JumpCut.跳剪(file,
  File "/opt/anaconda3/envs/jumpcutter/lib/python3.9/site-packages/JumpCutter2/JumpCut.py", line 462, in 跳剪
    if not 查询结果['streams']: # 没有视频轨
KeyError: 'streams'

$ ffprobe -of json -select_streams v -show_streams 20210916.mp4 
ffprobe version 4.3 Copyright (c) 2007-2020 the FFmpeg developers
  built with gcc 7.3.0 (crosstool-NG 1.23.0.449-a04d0)
  configuration: --prefix=/opt/conda/conda-bld/ffmpeg_1597178665428/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh --cc=/opt/conda/conda-bld/ffmpeg_1597178665428/_build_env/bin/x86_64-conda_cos6-linux-gnu-cc --disable-doc --disable-openssl --enable-avresample --enable-gnutls --enable-hardcoded-tables --enable-libfreetype --enable-libopenh264 --enable-pic --enable-pthreads --enable-shared --disable-static --enable-version3 --enable-zlib --enable-libmp3lame
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
{
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '20210916.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.45.100
  Duration: 00:01:34.65, start: 0.000000, bitrate: 937 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709), 608x1080 [SAR 1:1 DAR 76:135], 804 kb/s, 25 fps, 25 tbr, 12800 tbn, 50 tbc (default)
    Metadata:
      handler_name    : ISO Media file produced by Google Inc.
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 128 kb/s (default)
    Metadata:
      handler_name    : ISO Media file produced by Google Inc.
    "streams": [
        {
            "index": 0,
            "codec_name": "h264",
            "codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
            "profile": "High",
            "codec_type": "video",
            "codec_time_base": "1/50",
            "codec_tag_string": "avc1",
            "codec_tag": "0x31637661",
            "width": 608,
            "height": 1080,
            "coded_width": 608,
            "coded_height": 1088,
            "closed_captions": 0,
            "has_b_frames": 1,
            "sample_aspect_ratio": "1:1",
            "display_aspect_ratio": "76:135",
            "pix_fmt": "yuv420p",
            "level": 31,
            "color_range": "tv",
            "color_space": "bt709",
            "color_transfer": "bt709",
            "color_primaries": "bt709",
            "chroma_location": "left",
            "refs": 1,
            "is_avc": "true",
            "nal_length_size": "4",
            "r_frame_rate": "25/1",
            "avg_frame_rate": "25/1",
            "time_base": "1/12800",
            "start_pts": 0,
            "start_time": "0.000000",
            "duration_ts": 1209856,
            "duration": "94.520000",
            "bit_rate": "804867",
            "bits_per_raw_sample": "8",
            "nb_frames": "2363",
            "disposition": {
                "default": 1,
                "dub": 0,
                "original": 0,
                "comment": 0,
                "lyrics": 0,
                "karaoke": 0,
                "forced": 0,
                "hearing_impaired": 0,
                "visual_impaired": 0,
                "clean_effects": 0,
                "attached_pic": 0,
                "timed_thumbnails": 0
            },
            "tags": {
                "language": "und",
                "handler_name": "ISO Media file produced by Google Inc."
            }
        }
    ]
}

**Comment by tailangjun** [comment]
是不是 streams要改成大写的 Stream呀
